version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: minato1@
      MYSQL_DATABASE: bal_sheet
      MYSQL_USER: minato
      MYSQL_PASSWORD: minato1@
    volumes:
      - ./mysql-data:/var/lib/mysql

  # Node.js App
  web:
    image: node:14
    container_name: my_node_app
    working_dir: /usr/src/app
    dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
    links:
      - mysql